from __future__ import annotations

from typing import List


class Andrade:
    @staticmethod
    def text(index: int) -> str:
        return Andrade.strText[index]

    strText: List[str] = [
			"http:#www.yitoons.com/yibook2/images/YiBook2-111.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-112.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-113.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-114.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-115.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-116.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-117.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-118.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-119.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-121.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-122.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-123.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-124.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-125.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-126.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-127.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-128.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-129.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-130.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-131.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-132.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-133.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-134.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-135.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-136.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-137.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-138.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-139.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-140.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-141.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-142.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-143.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-144.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-145.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-146.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-147.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-148.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-149.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-150.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-151.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-152.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-153.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-154.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-155.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-156.jpg",
			"http:#www.yitoons.com/yibook2/images/YiBook2-157.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-102.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-103.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-104.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-105.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-106.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-107.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-108.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-109.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-110.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-111.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-112.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-113.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-114.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-115.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-116.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-117.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-118.jpg",
			"http:#www.yitoons.com/yibook3/images/YiBook3-119.jpg",
		]
